image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - test
  - deploy

XSharp-test:
  stage: test
  script:
    - apt-get update && apt-get -y install build-essential python3
    - make install-cosmos
    - cd ./XSharp.Zarlo.UNitTest
    - dotnet test

XSharp-deploy:
  stage: deploy
  script:
    - apt-get update && apt-get -y install build-essential python3
    - make install-cosmos
    - ./CICD/build_and_push_nuget.sh ./XSharp.Zarlo

Plugs:
  stage: deploy
  script:
    - apt-get update && apt-get -y install build-essential python3
    - make install-cosmos
    - ./CICD/build_and_push_nuget.sh ./Cosmos.Zarlo.Plugs

Zarlo:
  stage: deploy
  script:
    - apt-get update && apt-get -y install build-essential python3
    - make install-cosmos
    - ./CICD/build_and_push_nuget.sh ./Cosmos.Zarlo

Logger:
  stage: deploy
  script:
    - apt-get update && apt-get -y install build-essential python3
    - make install-cosmos
    - ./CICD/build_and_push_nuget.sh ./Cosmos.Zarlo.Logger

Memory:
  stage: deploy
  script:
    - apt-get update && apt-get -y install build-essential python3
    - make install-cosmos
    - ./CICD/build_and_push_nuget.sh ./Cosmos.Zarlo.Memory

Threading:
  stage: deploy
  script:
    - apt-get update && apt-get -y install build-essential python3
    - make install-cosmos
    - ./CICD/build_and_push_nuget.sh ./Cosmos.Zarlo.Threading

Threading.Mutex:
  stage: deploy
  script:
    - apt-get update && apt-get -y install build-essential python3
    - make install-cosmos
    - ./CICD/build_and_push_nuget.sh ./Cosmos.Zarlo.Threading.Mutex

FileSystems:
  stage: deploy
  script:
    - apt-get update && apt-get -y install build-essential python3
    - make install-cosmos
    - ./CICD/build_and_push_nuget.sh ./Cosmos.Zarlo.FileSystems




