default:
  image: mcr.microsoft.com/dotnet/sdk:6.0
  before_script:
    - apt-get update && apt-get -y install build-essential python3
    - make install-cosmos
  cache:
    key: cosmos-cache-$CI_COMMIT_REF_SLUG
    paths:
      - cosmos/
  artifacts:
    exclude:
      - cosmos/**
    paths:
      - "**/*.nupkg"
    expire_in: 1 day
 
stages:
  - test
  - deploy


XSharp-test:
  stage: test
  script:
    - cd ./Zarlo.XSharp.UNitTest
    - dotnet test

XSharp-deploy:
  stage: deploy
  script:
    - ./CICD/build_and_push_nuget.sh ./Zarlo.XSharp

Plugs:
  stage: deploy
  script:
    - ./CICD/build_and_push_nuget.sh ./Zarlo.Cosmos.Plugs

Zarlo:
  stage: deploy
  script:
    - ./CICD/build_and_push_nuget.sh ./Zarlo.Cosmos

Zarlo.Core:
  stage: deploy
  script:
    - ./CICD/build_and_push_nuget.sh ./Zarlo.Cosmos.Core

Zarlo.Common:
  stage: deploy
  script:
    - ./CICD/build_and_push_nuget.sh ./Zarlo.Cosmos.Common

Logger:
  stage: deploy
  script:
    - ./CICD/build_and_push_nuget.sh ./Zarlo.Cosmos.Logger

Memory:
  stage: deploy
  script:
    - ./CICD/build_and_push_nuget.sh ./Zarlo.Cosmos.Memory

Threading:
  stage: deploy
  script:
    - ./CICD/build_and_push_nuget.sh ./Zarlo.Cosmos.Threading

Threading.Mutex:
  stage: deploy
  script:
    - ./CICD/build_and_push_nuget.sh ./Zarlo.Cosmos.Threading.Mutex

Threading.Plug:
  stage: deploy
  script:
    - ./CICD/build_and_push_nuget.sh ./Zarlo.Cosmos.Threading.Plugs

Limine:
  stage: deploy
  script:
    - ./CICD/build_and_push_nuget.sh ./Zarlo.Cosmos.Limine

FileSystems:
  stage: deploy
  script:
    - ./CICD/build_and_push_nuget.sh ./Zarlo.Cosmos.FileSystems




