default:
  image: $CI_REGISTRY_IMAGE:76
  artifacts:
    exclude:
      - cosmos/**
    paths:
      - "**/*.nupkg"
    expire_in: 1 day

stages:
  - setup
  - test
  - build
  - deploy

pages:
  stage: deploy
  script:
    - dotnet build ./Liquip.NoTests.sln
    - dotnet tool update -g docfx
    - cd ./docfx && ~/.dotnet/tools/docfx metadata && ~/.dotnet/tools/docfx build -o ./../public
  artifacts:
    paths:
      - public

docker-setup:
  stage: setup
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/CICD/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_PIPELINE_IID}"

XSharp-test:
  stage: test
  script:
    - cd ./Tests/UNit/Liquip.XSharp.UNitTest
    - dotnet test
  only:
    changes:
      - Liquip.XSharp/**/*
      - Liquip.XSharp/**
      - Tests/UNit/Liquip.XSharp.UNitTest/**
      - Tests/UNit/Liquip.XSharp.UNitTest/**/*

XSharp-deploy:
  stage: build
  script:
    - ./CICD/build_and_push_nuget.sh ./Liquip.XSharp
  only:
    changes:
      - Liquip.XSharp/**/*
      - Liquip.XSharp/**
      - Tests/UNit/Liquip.XSharp.UNitTest/**
      - Tests/UNit/Liquip.XSharp.UNitTest/**/*

Plugs:
  stage: build
  script:
    - ./CICD/build_and_push_nuget.sh ./Liquip.Plugs


Liquip:
  stage: build
  script:
    - ./CICD/build_and_push_nuget.sh ./Liquip


Liquip.Core:
  stage: build
  script:
    - ./CICD/build_and_push_nuget.sh ./Liquip.Core


Liquip.Common:
  stage: build
  script:
    - ./CICD/build_and_push_nuget.sh ./Liquip.Common


Logger:
  stage: build
  script:
    - ./CICD/build_and_push_nuget.sh ./Liquip.Logger



Memory:
  stage: build
  script:
    - ./CICD/build_and_push_nuget.sh ./Liquip.Memory

Threading:
  stage: build
  script:
    - ./CICD/build_and_push_nuget.sh ./Liquip.Threading


Threading.Plug:
  stage: build
  script:
    - ./CICD/build_and_push_nuget.sh ./Liquip.Threading.Plugs


Limine:
  stage: build
  script:
    - ./CICD/build_and_push_nuget.sh ./Liquip.Limine


FileSystems:
  stage: build
  script:
    - ./CICD/build_and_push_nuget.sh ./Liquip.FileSystems


VirtIO:
  stage: build
  script:
    - ./CICD/build_and_push_nuget.sh ./Liquip.Driver.VirtIO


CosmosManager:
  stage: build
  script:
    - ./CICD/build_and_push_nuget.sh ./CosmosManager
  only:
    changes:
      - CosmosManager/**
