namespace Zarlo.Cosmos.Driver.VirtIO.GPU.Struct;


public enum GpuCmd: int
{
    GET_DISPLAY_INFO = 0x0100,
    RESOURCE_CREATE_2D,
    RESOURCE_UNREF,
    SET_SCANOUT,
    RESOURCE_FLUSH,
    TRANSFER_TO_HOST_2D,
    RESOURCE_ATTACH_BACKING,
    RESOURCE_DETACH_BACKING,
    GET_CAPSET_INFO,
    GET_CAPSET,
    GET_EDID,
    /* cursor commands */
    UPDATE_CURSOR = 0x0300,
    MOVE_CURSOR,
    /* success responses */
    RESP_OK_NODATA = 0x1100,
    RESP_OK_DISPLAY_INFO,
    RESP_OK_CAPSET_INFO,
    RESP_OK_CAPSET,
    RESP_OK_EDID,
    /* error responses */
    RESP_ERR_UNSPEC = 0x1200,
    RESP_ERR_OUT_OF_MEMORY,
    RESP_ERR_INVALID_SCANOUT_ID,
    RESP_ERR_INVALID_RESOURCE_ID,
    RESP_ERR_INVALID_CONTEXT_ID,
    RESP_ERR_INVALID_PARAMETER
}

public enum GpuFormats: int
{
    B8G8R8A8_UNORM = 1,
    B8G8R8X8_UNORM = 2,
    A8R8G8B8_UNORM = 3,
    X8R8G8B8_UNORM = 4,
    R8G8B8A8_UNORM = 67,
    X8B8G8R8_UNORM = 68,
    A8B8G8R8_UNORM = 121,
    R8G8B8X8_UNORM = 134,
};
