cosmos-install:
	CosmosManager install

cosmos-update:
	CosmosManager update

cosmos-lock:
	CosmosManager lock

cosmos-info:
	CosmosManager info

build: clean
	dotnet build

clean:
	dotnet clean

package: build
	dotent package
