namespace Liquip.Driver.VirtIO;

public enum DeviceTypeVirtIO : ushort
{
    Reserved = 4160 + 0,
    NetworkCard = 4160 + 1,
    BlockDevice = 4160 + 2,
    Console = 4160 + 3,
    EntropySource = 4160 + 4,
    MemoryBallooning = 4160 + 5,
    IoMemory = 4160 + 6,
    Rpmsg = 4160 + 7,
    SCSIhost = 4160 + 8,
    _9PTransport = 4160 + 9,
    Mac80211Wlan = 4160 + 10,
    RprocSerial = 4160 + 11,
    VirtioCAIF = 4160 + 12,
    MemoryBalloon = 4160 + 13,
    GPU_device = 4160 + 16,
    Timer_ClockDevice = 4160 + 17,
    InputDevice = 4160 + 18,
    SocketDevice = 4160 + 19,
    CryptoDevice = 4160 + 20,
    SignalDistributionModule = 4160 + 21,
    PstoreDevice = 4160 + 22,
    IOMMU_device = 4160 + 23,
    MemoryDevice = 4160 + 24,
    AudioDevice = 4160 + 25,
    FileSystemDevice = 4160 + 26,
    PMEMDevice = 4160 + 27,
    RPMBDevice = 4160 + 28,
    Mac80211HwsimWirelessSimulationDevice = 4160 + 29,
    VideoEncoderDevice = 4160 + 30,
    VideoDecoderDevice = 4160 + 31,
    SCMIDevice = 4160 + 32,
    NitroSecureModule = 4160 + 33,
    I2C_adapter = 4160 + 34,
    Watchdog = 4160 + 35,
    CAN_device = 4160 + 36,
    ParameterServer = 4160 + 38,
    AudioPolicyDevice = 4160 + 39,
    BluetoothDevice = 4160 + 40,
    GPIO_device = 4160 + 41,
    RDMA_device = 4160 + 42
}

public static class DeviceTypeVirtIOEx
{
    public static string AsString(this DeviceTypeVirtIO me) =>
        me switch
        {
            DeviceTypeVirtIO.Reserved => "Reserved",
            DeviceTypeVirtIO.NetworkCard => "NetworkCard",
            DeviceTypeVirtIO.BlockDevice => "BlockDevice",
            DeviceTypeVirtIO.Console => "Console",
            DeviceTypeVirtIO.EntropySource => "EntropySource",
            DeviceTypeVirtIO.MemoryBallooning => "MemoryBallooning",
            DeviceTypeVirtIO.IoMemory => "IoMemory",
            DeviceTypeVirtIO.Rpmsg => "Rpmsg",
            DeviceTypeVirtIO.SCSIhost => "SCSIhost",
            DeviceTypeVirtIO._9PTransport => "_9PTransport",
            DeviceTypeVirtIO.Mac80211Wlan => "Mac80211Wlan",
            DeviceTypeVirtIO.RprocSerial => "RprocSerial",
            DeviceTypeVirtIO.VirtioCAIF => "VirtioCAIF",
            DeviceTypeVirtIO.MemoryBalloon => "MemoryBalloon",
            DeviceTypeVirtIO.GPU_device => "GPU_device",
            DeviceTypeVirtIO.Timer_ClockDevice => "Timer_ClockDevice",
            DeviceTypeVirtIO.InputDevice => "InputDevice",
            DeviceTypeVirtIO.SocketDevice => "SocketDevice",
            DeviceTypeVirtIO.CryptoDevice => "CryptoDevice",
            DeviceTypeVirtIO.SignalDistributionModule => "SignalDistributionModule",
            DeviceTypeVirtIO.PstoreDevice => "PstoreDevice",
            DeviceTypeVirtIO.IOMMU_device => "IOMMU_device",
            DeviceTypeVirtIO.MemoryDevice => "MemoryDevice",
            DeviceTypeVirtIO.AudioDevice => "AudioDevice",
            DeviceTypeVirtIO.FileSystemDevice => "FileSystemDevice",
            DeviceTypeVirtIO.PMEMDevice => "PMEMDevice",
            DeviceTypeVirtIO.RPMBDevice => "RPMBDevice",
            DeviceTypeVirtIO.Mac80211HwsimWirelessSimulationDevice => "Mac80211HwsimWirelessSimulationDevice",
            DeviceTypeVirtIO.VideoEncoderDevice => "VideoEncoderDevice",
            DeviceTypeVirtIO.VideoDecoderDevice => "VideoDecoderDevice",
            DeviceTypeVirtIO.SCMIDevice => "SCMIDevice",
            DeviceTypeVirtIO.NitroSecureModule => "NitroSecureModule",
            DeviceTypeVirtIO.I2C_adapter => "I2C_adapter",
            DeviceTypeVirtIO.Watchdog => "Watchdog",
            DeviceTypeVirtIO.CAN_device => "CAN_device",
            DeviceTypeVirtIO.ParameterServer => "ParameterServer",
            DeviceTypeVirtIO.AudioPolicyDevice => "AudioPolicyDevice",
            DeviceTypeVirtIO.BluetoothDevice => "BluetoothDevice",
            DeviceTypeVirtIO.GPIO_device => "GPIO_device",
            DeviceTypeVirtIO.RDMA_device => "RDMA_device",
            _ => "unknown" + (int)me
        };
}
